### ISSUE TITLE
Export the result to GeoTIFF

### ISSUE THREAD

**Issue by firmanhadi** [ptitle/epm#1]
Dear @ptitle,

Thank you for creating the package.
I would like to ask how to export the result (epmGrid) to GeoTIFF for plotting in QGIS.
Thank you.

Regards,

Firman.

**Comment by ptitle** [comment]
I'm planning on writing a small dedicated function for this to be included in the package, but in the meantime, if the epm object is called xx:

```
# if this is a hexagonal grid epm object
sf::st_write(xx[[1]][attributes(xx)$metric], 'epmSpatial.shp')

# if this is a square grid epm object
terra::writeRaster(xx[[1]][attributes(xx)$metric], '~/Downloads/epmSpatial.tif')
```
