### ISSUE TITLE
createEPMgrid with single table of coordinates

### ISSUE THREAD

**Issue by jenifferteles** [ptitle/epm#2]
Hello, I’m trying to create a createEPMgrid object with my occurring points. But in the examples in the pdf of the package, I’m not getting because when creating the createEPMgrid it does with the raw data of "spOccList" and not with the created object called "spOccList3" as in the case below. How can I fix this? Thank you

# single table of coordinates
spOccList3 <- spOccList2
for (i in 1:length(spOccList3)) {
	spOccList3[[i]] <- cbind.data.frame(taxon = names(spOccList3)[i], spOccList3[[i]])
	colnames(spOccList3[[i]]) <- c('taxon', 'X', 'Y')
}
spOccList3 <- do.call(rbind, spOccList3)
rownames(spOccList3) <- NULL
spOccList3[, "taxon"] <- as.character(spOccList3[, "taxon"])
tamiasEPM <- createEPMgrid(**spOccList**, resolution = 100000, cellType = 'square')

**Comment by ptitle** [comment]
Hi,
I fixed a problem and also corrected some mistakes in the example code from `createEPMgrid()`. Please install from github with `remotes::install_github('ptitle/epm')` and try again and let me know if this solves your issue!

**Comment by jenifferteles** [comment]
Thank you, one last question in the crs part I tried to put only the code I need (crs = 4674), but gives the following error:

Detected 119 taxa with point data.
Error in createEPMgrid(dataOK, resolution = 1e+05, cellType = "square",  : 
  Input data are in longlat, therefore resolution must be in decimal degrees.

Do I necessarily need a SpatRaster file to copy crs as the example? 

I used the following command for #single table of coordinates :

CriarEPM <- createEPMgrid(dataOK, resolution = 100000, cellType = 'square',  crs = 4674)

Thank you so much!!!

**Comment by ptitle** [comment]
Hi,
No, you can provide the crs directly as a code, such as `crs = 4674`. The problem here is that your coordinates are in longitude/latitude, and you provided a resolution of 100k. The resolution is assumed to be in the same units as the coordinates. So you should either transform your coordinates into a projected system in meters, or provide the resolution in decimal degree units. Make sense?

**Comment by jenifferteles** [comment]
Yeah Totally! Perfect, thank you so much!

**Comment by ptitle** [comment]
Great, good to hear this makes sense. Please post any other issues!
