### ISSUE TITLE
createEPMgrid dropping many maps

### ISSUE THREAD

**Issue by TomLansley** [ptitle/epm#3]
I am trying to create a grid with 16003 maps, each in Multipolygon format. Each time, around 5590 maps are dropped (but not exactly the same number). I have tried with several options and using the centroid method seems to retain more but still drops far more than I would like. I have also tried using the verbose option which gives the error: "Failed to compute min/max, no valid pixels found in sampling. (GDAL error 1)". It's possible that the size of the maps is an issue with terra. I will try using hexagon cell types next to see if that helps. I am using Key Biodiversity Areas https://www.keybiodiversityareas.org/sites/search. 

Any help would be appreciated! let me know if I can give you more information. 
Thanks,
Tom

This is the code:
#read in KBA polgons
kbas <- here::here("Data/Spatial_data/kbas_minus_nine_invalid.shp") %>%
  st_read()

table(st_is_valid(kbas)) #all valid, but still a lot get dropped when making the grid

KBAList <- vector('list', length(unique(kbas$SitRecID))) #list of all KBAs
names(KBAList) <- unique(kbas$SitRecID) #each unique name, no duplicates

#use a 'for' loop add KBAs to the list
for (i in 1:length(KBAList)) {
  KBAList[[i]] <- kbas[i,]
  print(i)
}

EAproj <- "+proj=cea +lat_ts=30 +units=km" #set Berhmann projection, units as km
KBAListEA <- lapply(KBAList, function(x) st_transform(x, st_crs(EAproj))) # apply the projection to the maps
#16003 maps - one for each KBA

write_rds(KBAListEA, "Data/My_data/KBAListEA")
KBAListEA <- read_rds("Data/My_data/KBAListEA") 

#create the grid
KBAs_grid <- createEPMgrid(KBAListEA, resolution = 100, extent = "auto", cellType = "square", method="percentOverlap", percentThreshold=0.1, retainSmallRanges =TRUE)
#5590 maps dropped, so only 10413 left.

**Comment by ptitle** [comment]
Hi,

Do you mind sending me the file `Data/Spatial_data/kbas_minus_nine_invalid.shp`? Then I can replicate what you are dealing with and see if this is a bug or something inherent to your dataset. My email is pascal.title[at]stonybrook.edu. Thanks!

**Comment by ptitle** [comment]
This has been fixed.
