### ISSUE TITLE
Issue with customGridMetric

### ISSUE THREAD

**Issue by LiamMacNeil** [ptitle/epm#5]
Hello,

First, the paper and package seem great. Thanks for your hard work. 

I am having an issue calculating a grid cell dissimilarity measure (`customGridMetric`) using categorical traits. E.g., a Gower's dissimilarity from the `FD` (functional diversity) package. Even a simple, reduced example.

A small subsample has been attached here (zipped) for reproduction.

[testing.zip](https://github.com/ptitle/epm/files/14087464/testing.zip)

# 
```
EPM<- read.epmGrid("testing.rds")

taxa <- rownames(EPM$data)
dat <- EPM$data
phylo <- EPM$phylo

obs_dist <- function(taxa) {
  gowdis(dat[taxa,])
}

dist<- epm::customGridMetric(EPM_phylo_trait, 
                                  fun = obs_dist, 
                                  minTaxCount = 2, 
                                  metricName = "Gower's")
```

gives:

`Error in is.nan(resVal) : default method not implemented for type 'list'`

It seems sourced from the `# Assemble results` section and maybe related to 

https://stackoverflow.com/questions/75476271/default-method-not-implemented-for-type-list-is-there-anything-i-can-do

or similar

https://github.com/ycphs/openxlsx/issues/158

Any insight or tips would be greatly helpful.

**Comment by ptitle** [comment]
Hi Liam,

For any given cell with some subset of taxa, the gowdis() function will return a pairwise distance matrix. However, the customGridMetric function is expecting that whatever function is defined returns a single value that will represent a particular grid cell. 

So if you want to use Gower's distance, you need to add some sort of summary statistic. 

For example, let's say we took the max of the returned Gower's distance matrix:

```
obs_dist <- function(taxa) {
   max(gowdis(dat[taxa,]))
}

dist<- epm::customGridMetric(EPM, 
                                  fun = obs_dist, 
                                  minTaxCount = 2, 
                                  metricName = "Gower's")

```
This works for me. It may not a reasonable solution, but should hopefully illustrate what I mean.

Does that make sense?

**Comment by LiamMacNeil** [comment]
Hi Pascal,

Thank you for the fast and clear reply. It makes sense and the error obvious to me now. I'll think more about a proper interpretation or use for this kind of dissimilarity. 

Cheers!

**Comment by ptitle** [comment]
No problem -- perhaps a min or mean nearest neighbor distance, or something along those lines.
